return {
  text_icons = {
    ActiveLSP = "LSP:",
    ActiveTS = "",
    BufferClose = "x",
    DefaultFile = "[F]",
    Diagnostic = "",
    DiagnosticError = "X",
    DiagnosticHint = "?",
    DiagnosticInfo = "i",
    DiagnosticWarn = "!",
    Ellipsis = "...",
    FileModified = "*",
    FileReadOnly = "[lock]",
    FolderClosed = "[D]",
    FolderEmpty = "[E]",
    FolderOpen = "[O]",
    Git = "",
    GitAdd = "[+]",
    GitBranch = "",
    GitChange = "[/]",
    GitConflict = "[!]",
    GitDelete = "[-]",
    GitIgnored = "[I]",
    GitRenamed = "[R]",
    GitStaged = "[S]",
    GitUnstaged = "[U]",
    GitUntracked = "[?]",
    LSPLoaded = "",
    LSPLoading1 = "",
    LSPLoading2 = "",
    LSPLoading3 = "",
    MacroRecording = "Recording:",
    NeovimClose = "X",
  },
}
